baseURL = 'https://pedogee.com/'
languageCode = 'en-us'
title = 'Pedogee = Simplified'

[server]
CORSOrigins = ["http://localhost:1313", "http://127.0.0.1:1313", "https://www.pedogee.com", "https://pedogee.com"]
